on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Build manylinux Python wheels
      uses: RalfG/python-wheels-manylinux-build@v0.5.0-manylinux2014_x86_64
      with:
        python-versions: 'cp39-cp39'
        build-requirements: 'twine'
        system-packages: 'guile-devel zlib-devel gettext portaudio-devel portmidi-devel libsndfile-devel alsa-lib-devel autogen libdb-devel wget jack-audio-connection-kit-devel'
        pre-build-command: 'sh manylinux-pre-build-script.sh'
        pip-wheel-args: '-w ./dist --build-option --use-double --build-option --use-jack'
    - name: Publish wheels to test PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        /opt/python/cp39-cp39/bin/twine upload --repository testpypi dist/*-manylinux*.whl